CREATE TABLE IF NOT EXISTS plante (
    id INT AUTO_INCREMENT,
    name VARCHAR(80) NOT NULL,
    categorie VARCHAR(80) NOT NULL,
    description VARCHAR(255) NOT NULL,
    picture_url VARCHAR(255) NOT NULL,
    humydite INT,
    temperature INT,
    luminosite INT,
    periode VARCHAR(80),
    PRIMARY KEY (id)
)  ENGINE=INNODB;

INSERT INTO plante (name, categorie, description, picture_url, humydite, temperature, luminosite, periode)
VALUES ('Rosier', 'arbuste à fleurs, plante grimpante', 'C est au moyen-âge que les premières roses ont été cultivées, elles furent importées par les croisés en provenance de l orient. ( Au soleil à l abri du vent )', './images/rosier.jpg', '50', '70', '70', '4'),
('Absinthe', 'Botanique', 'L’absinthe est plus connue et renommée pour sa liqueur que pour ses nombreux avantages au jardin. Elle est aromatique, elle a de nombreuses vertus médicinales et s’avère être un bon répulsif au potager. ', './images/absinthe.jpg', '50', '20', '40', '8'),
('plante3', 'categorie3', 'description.......', 'http://art21.fr/wp-content/uploads/2015/09/photo-histoire-einstein-tire-langue.jpg', '60', '30', '40', '4'),
('plante4', 'categorie4', 'description.......', 'http://art21.fr/wp-content/uploads/2015/09/photo-histoire-einstein-tire-langue.jpg', '60', '30', '40', '4'),
('plante5', 'categorie4', 'description.......', 'http://art21.fr/wp-content/uploads/2015/09/photo-histoire-einstein-tire-langue.jpg', '60', '30', '40', '4'),
('plante6', 'categorie4', 'description.......', 'http://art21.fr/wp-content/uploads/2015/09/photo-histoire-einstein-tire-langue.jpg', '60', '30', '40', '4'),
('plante7', 'categorie4', 'description.......', 'http://art21.fr/wp-content/uploads/2015/09/photo-histoire-einstein-tire-langue.jpg', '60', '30', '40', '4'),
('plante8', 'categorie4', 'description.......', 'http://art21.fr/wp-content/uploads/2015/09/photo-histoire-einstein-tire-langue.jpg', '60', '30', '40', '4'),
('plante9', 'categorie4', 'description.......', 'http://art21.fr/wp-content/uploads/2015/09/photo-histoire-einstein-tire-langue.jpg', '60', '30', '40', '4'),
('plante10', 'categorie4', 'description.......', 'http://art21.fr/wp-content/uploads/2015/09/photo-histoire-einstein-tire-langue.jpg', '60', '30', '40', '4'),
('plante11', 'categorie4', 'description.......', 'http://art21.fr/wp-content/uploads/2015/09/photo-histoire-einstein-tire-langue.jpg', '60', '30', '40', '4'),
('plante12', 'categorie4', 'description.......', 'http://art21.fr/wp-content/uploads/2015/09/photo-histoire-einstein-tire-langue.jpg', '60', '30', '40', '4'),
('plante13', 'categorie4', 'description.......', 'http://art21.fr/wp-content/uploads/2015/09/photo-histoire-einstein-tire-langue.jpg', '60', '30', '40', '4'),
('plante14', 'categorie4', 'description.......', 'http://art21.fr/wp-content/uploads/2015/09/photo-histoire-einstein-tire-langue.jpg', '60', '30', '40', '4'),
('plante15', 'categorie4', 'description.......', 'http://art21.fr/wp-content/uploads/2015/09/photo-histoire-einstein-tire-langue.jpg', '60', '30', '40', '4'),
('plante16', 'categorie4', 'description.......', 'http://art21.fr/wp-content/uploads/2015/09/photo-histoire-einstein-tire-langue.jpg', '60', '30', '40', '4'),
('plante17', 'categorie4', 'description.......', 'http://art21.fr/wp-content/uploads/2015/09/photo-histoire-einstein-tire-langue.jpg', '60', '30', '40', '4'),
('plante18', 'categorie4', 'description.......', 'http://art21.fr/wp-content/uploads/2015/09/photo-histoire-einstein-tire-langue.jpg', '60', '30', '40', '4'),
('plante19', 'categorie4', 'description.......', 'http://art21.fr/wp-content/uploads/2015/09/photo-histoire-einstein-tire-langue.jpg', '60', '30', '40', '4'),
('plante20', 'categorie4', 'description.......', 'http://art21.fr/wp-content/uploads/2015/09/photo-histoire-einstein-tire-langue.jpg', '60', '30', '40', '4'),
('plante21', 'categorie4', 'description.......', 'http://art21.fr/wp-content/uploads/2015/09/photo-histoire-einstein-tire-langue.jpg', '60', '30', '40', '4'),
('plante22', 'categorie4', 'description.......', 'http://art21.fr/wp-content/uploads/2015/09/photo-histoire-einstein-tire-langue.jpg', '60', '30', '40', '4'),
('plante23', 'categorie4', 'description.......', 'http://art21.fr/wp-content/uploads/2015/09/photo-histoire-einstein-tire-langue.jpg', '60', '30', '40', '4'),
('plante24', 'categorie4', 'description.......', 'http://art21.fr/wp-content/uploads/2015/09/photo-histoire-einstein-tire-langue.jpg', '60', '30', '40', '4'),
('plante25', 'categorie4', 'description.......', 'http://art21.fr/wp-content/uploads/2015/09/photo-histoire-einstein-tire-langue.jpg', '60', '30', '40', '4'),
('plante26', 'categorie4', 'description.......', 'http://art21.fr/wp-content/uploads/2015/09/photo-histoire-einstein-tire-langue.jpg', '60', '30', '40', '4'),
('plante27', 'categorie4', 'description.......', 'http://art21.fr/wp-content/uploads/2015/09/photo-histoire-einstein-tire-langue.jpg', '60', '30', '40', '4'),
('plante28', 'categorie4', 'description.......', 'http://art21.fr/wp-content/uploads/2015/09/photo-histoire-einstein-tire-langue.jpg', '60', '30', '40', '4'),
('plante29', 'categorie4', 'description.......', 'http://art21.fr/wp-content/uploads/2015/09/photo-histoire-einstein-tire-langue.jpg', '60', '30', '40', '4'),
('plante30', 'categorie4', 'description.......', 'http://art21.fr/wp-content/uploads/2015/09/photo-histoire-einstein-tire-langue.jpg', '60', '30', '40', '4')
